MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  ATSS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1
  RETINANET:
    USE_C5: False
  ATSS:
    ANCHOR_SIZES: (64, 128, 256, 512, 1024) # 8S
    ASPECT_RATIOS: (1.0,)
    SCALES_PER_OCTAVE: 1
    USE_DCN_IN_TOWER: True
    POSITIVE_TYPE: 'ATSS' # how to select positves: ATSS (Ours) , SSC (FCOS), IoU (RetinaNet)
    TOPK: 9 # topk for selecting candidate positive samples from each level
    REGRESSION_TYPE: 'BOX' # regressing from a 'BOX' or a 'POINT'
DATASETS:
  TRAIN: ("coco_2017_train",)
  #TEST: ("coco_2017_val",)
  TEST: ("coco_2017_test_dev",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
##################################################################################
## Original configuration ##
#SOLVER:
#  BASE_LR: 0.01
#  WEIGHT_DECAY: 0.0001
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
#  IMS_PER_BATCH: 16
#  WARMUP_METHOD: "constant"

##################################################################################
#SOLVER:
#  BASE_LR: 0.001
#  WEIGHT_DECAY: 0.0001
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
#  IMS_PER_BATCH: 16  # batch size # 16-8-4
#  WARMUP_METHOD: "constant"
#  CHECKPOINT_PERIOD: 2500  # candidate choice are 2500 , 3000 , 5000 , 10000
#  EPOCH: 1  # default:1 ,1 2 3 4 5 6 are CANDIDATED

##################################################################################
## For first-training in lab #501 with 2080Ti and 2 GPUs ##
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  MAX_ITER: 360000
  IMS_PER_BATCH: 4  # batch size # 16-8-4
  WARMUP_METHOD: "constant"
  CHECKPOINT_PERIOD: 10000  # candidate choice are 2500 , 3000 , 5000 , 10000
  EPOCH: 1  # default:1 ,1 2 3 4 5 6 are CANDIDATED

####################################################################################
## For fine-training in lab #501 with 2080Ti and 2 GPUs ##
## based on original pth file -> LOAD_PTH: "/home/alanc/Documents/ATSS/trained_pth/ATSS_R_50_FPN_1x.pth" ##
#SOLVER:
#  BASE_LR: 0.001
#  WEIGHT_DECAY: 0.0001
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
#  IMS_PER_BATCH: 4  # batch size # 16-8-4
#  WARMUP_METHOD: "constant"
#  CHECKPOINT_PERIOD: 10000  # candidate choice are 2500 , 3000 , 5000 , 10000
#  EPOCH: 1  # default:1 ,1 2 3 4 5 6 are CANDIDATED

###################################################################################